[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
private_state_toolkit = "4FeUYtneSbfieLwjUT1ceHtv8nDXFk2autCZFyDhpkeD"
pst_consumer = "BxqCdUzNrMifua7Rd3qQSqgd4oyTzdcTqH1tbYuvi5bf"

[programs.testnet]
private_state_toolkit = "4FeUYtneSbfieLwjUT1ceHtv8nDXFk2autCZFyDhpkeD"
pst_consumer = "BxqCdUzNrMifua7Rd3qQSqgd4oyTzdcTqH1tbYuvi5bf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
